version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: supaHUB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: supaHUB_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DBUSER: admin
      DBPASS: admin
      DBHOST: db
      DBNAME: supaHUB
    ports:
      - "8080:8080"
    command: ["make", "run-server"]
